### ISSUE TITLE
Write base documentation

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#134]
Use Github wiki for general high level description for the cloud harness uses, READMEs for code structure description and cloudharness dev info.

**Comment by lrebscher** [comment]
* Add a section to the README with a simple example: (1) Create application with webapp + db template (2) Deploy application (3) Query endpoint to test if it is alive
* Add a sidebar entry listing all application templates + DBs that are available, also a good point to collect any further reading about the specific technologies and best practices

**Comment by filippomc** [comment]
![CloudHarness - Deployment Workflow](https://user-images.githubusercontent.com/46561561/107386264-f8e0a080-6af3-11eb-9cd2-e8045b273012.png)
![CloudHarness - Deployment Workflow (1)](https://user-images.githubusercontent.com/46561561/107386271-fa11cd80-6af3-11eb-8e1e-241fb6f00e36.png)
