### ISSUE TITLE
Question: how to extend the deployment so that you can choose per env (dev,test,stage,prod) yes or no database backups

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#191]

**Comment by filippomc** [comment]
1. Create or edit deployment-configuration/values-[ENV].yaml file
1. Change the backup value:
```yaml
backup:
   active: false
```

**Comment by zsinnema** [comment]
Ihave the impression that this is not working, when I create a values-prod.yaml with backup False
I run harness-deployment with -e prod
and then in the helm/value.yaml there is still backup true

**Comment by filippomc** [comment]
sorry the correct name is deployment-configuration/values-template-[ENV].yaml.

Correcting also the above answer

**Comment by zsinnema** [comment]
btw backup is by default enabled see https://github.com/MetaCell/cloud-harness/blob/f1270a12a59ebe1a980a05af5ce4ad2456e69204/utilities/cloudharness_utilities/deployment-configuration/helm/values.yaml#L49

but in the wiki it states default off 
https://github.com/MetaCell/cloud-harness/wiki/Databases#configuring-backups

**Comment by filippomc** [comment]
Maybe is good to be enabled by default, what do you think?

**Comment by zsinnema** [comment]
depends... when I'm developing I want it default off, when I'm sysadmin I want it default on

Because it's a CH thing which is a "development" component I would put it default to false
but I understand also when it's default true

**Comment by lrebscher** [comment]
that the backup is enabled by default is probably an unintentionally change of a following commit
