### ISSUE TITLE
Always use https

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#22]
in utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml there is this line:
` nginx.ingress.kubernetes.io/ssl-redirect: 'false'
`

I strongly advise to always use HTTPS and change this line to:
`nginx.ingress.kubernetes.io/ssl-redirect: 'true'
`

**Comment by filippomc** [comment]
@zsinnema agree, this was meant for local testing, as it's quite annoying to browse without trusted certificates. What about leaving it as false only when param `local` is set to true?
