### ISSUE TITLE
Wrong codefresh variable usage when deploying

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#232]
at the deployment step of the codefresh prod yaml the `DEPLOYMENT_PUBLISH_TAG` is used
imo it should be `DEPLOYMENT_TAG` instead

**Comment by filippomc** [comment]
The nomenclature may sound confusing but I think that the current implementation is correct: DEPLOYMENT_TAG is used to get the tag for the deployment (from a previous build), while DEPLOYMENT_PUBLISH_TAG, if specified, is meant to give a new tag after approval.
