### ISSUE TITLE
Improve caching in build pipeline

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#241]
Docker caching gets inactivated by different build arguments.
Specifically the TAG parameter changes from build to build but we are not necessarily building from a different base image as the parameter is changing anyway.

Possible solutions:
- Use some hashing value from file content to define build image tags instead of build id
- Always build on the "latest" tag and use "latest" parameter (beware that different pipelines may use the same image name!!)

**Comment by zsinnema** [comment]
I would like to add another option: build tag == commit id
and for sub repos use the commit id of the sub repo

e.g.
ifn = commit-ifn-123
mnp = commit-mnp-456
ch = commit-ch-789
then the ch images should use the ch commit id: commit-ch-789
mnp images: mnp commit id: commit-mnp-456
ifn images: ifn commit id: commit-ifn-123

in that case the image names are unique and cachable
