### ISSUE TITLE
Implement Integration/E2E test framework for applications

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/cloud-harness#248]
**Test Runner**

* Write a simple integration test for samples application and configure a [Kubernetes Job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) that executes the test
* Test result should determine if job succeeded/failed

**Test Report Storage**

* In a first iteration, we might start with simply using the job log output as additional information to the binary test result
* In a next step, we could define a persistent volume that is mounted in the test job and store the test results or allow to configure  a storage bucket that can be easily integrated with CI tools (e.g. CodeFresh).

**Test Watcher**

* Implement a new CLI tool `harness-test` that watches a test job in a configurable namespace of a K8s cluster. It waits for the job to finish and exits with 1/0 depending on the test results.
* It might also be the case that we want to have a test job per application, in that case we wait for more than one job.
* Log all test results to stdout
* Evaluate how we can best access test reports stored in a persistent volume outside of the K8s cluster 

**Deployment Flow**

* Since we first have to install the helm chart before we can run the integration tests, we might want to create a temporary namespace in which we can test the deployment. If tests succeed, we continue with deployment to the actual namespace.

**Configuration**

* Add a `auto-test.yaml` to the cloudharness templates that describes the K8s job
* We probably want to have the option to configure some parameters on the application level

```yaml
harness:
   test:
     enabled: false
     ...
```

It is still open if we want to have one test job, group test jobs based on testing tools or have one test job per application.

The complete flow is similar to the following:
![Bildschirmfoto 2021-03-02 um 11.47.47.png](https://images.zenhubusercontent.com/600fdb37a2c5e223bc039639/e577cced-6640-4af6-9e68-c7112e2a2644)

**Some useful sources and notes**

* The described approach was taken from [this article](https://medium.com/datasparq-technology/integration-tests-in-kubernetes-and-cloud-build-52a2b1023ab3)
* Also interesting but not dealing with application testing, rather as a last step to ensure that K8s resources are in place: https://github.com/bats-core/bats-detik
*  [Cicada](https://cicadatesting.github.io/cicada-2/) is worth a look, also based on yaml configuration, but it doesn't seem to be very flexible and development just started some months ago
* [kubetest2](https://github.com/kubernetes-sigs/kubetest2) and https://kubernetes.io/blog/2019/03/22/kubernetes-end-to-end-testing-for-everyone/ deal rather with testing K8s features than with application tests

**Comment by filippomc** [comment]
New workflow with tests
![CloudHarness - Deployment Workflow (2).png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/21e36538-8503-4310-b6f5-31dd94ae3b07)

**Comment by filippomc** [comment]
We may have a folder called `tests` with the same kind of structure of `tasks`, each application can define one or more test dockerfiles.
We can then run them as k8s jobs or use an Argo workflow to allow more sophisticated control (like having a first wait jov then the rest in parallel). Also the whole workflow will fail when one fails making the control easier

**Comment by filippomc** [comment]
Additional requirement: will add the concept of test deployment pipeline where automated end to end tests are performed. This deployment is created upon pull requests triggers and deleted after the test is performed![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/9beab031-39de-4d8d-9562-7a56270abcf1)

**Comment by filippomc** [comment]
# Proposed solution

Inside each application we add a `test` folder

```
myapp
  deploy
  ...
  test
     unit.yaml
    integration
    e2e
```

Tests are recognized by cloudharness, which will run them in the proper environment setup:
- **unit tests** run inside the built image, before the deployment. The `unit.yaml` file specifies the command(s) to use to run the tests inside the image from the main WORKDIR. The implementation of the tests is expected to be part of the application's source code and to be included in the image
- **integration tests** run inside a Python environment and target the api endpoints in the kubernetes deployment.
- **e2e tests** are specified in a node project, which is compiled and built in a dedicated image specifying the environment variable `BASE_URL`. The BASE_URL must be used as a target for the tests. The project implements two test scripts:
  - `smoketests`  (i.e runnable with `npm run smoketests`)
  - `functionaltests` (i.e runnable with `npm run functionaltests`)
