### ISSUE TITLE
Fix Argo ui detail page

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#278]
The detail page of Argo ui hangs and doesn't show the workflow details.
This is certainly related to the presence of the gatekeeper (it works without it).

One strategy may be to whitelist some api paths in the gk configuration.

**Comment by zsinnema** [comment]
I have not noticed this behaviour, both in minikube and in production (with gatekeeper).
can you describe how to reproduce?

**Comment by filippomc** [comment]
looks like it's fixed now. Closing

**Comment by zsinnema** [comment]
I would like to spend some time on testing the argo ui , sometimes it's unstable
