### ISSUE TITLE
Improve default exception handling in Flask backend apis

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#322]
Errors should include the error message and the stack trace

**Comment by zsinnema** [comment]
I would like to propose using of Sentry for this (client and server side)
Client side: use the sentry react error boundary for js (https://www.npmjs.com/package/@sentry/react), may be also invest some time in using this module https://www.npmjs.com/package/redux-sentry-middleware 
Server side: use the sentry python/java sdk

Imho the frontend doesn't need to log the error and stack trace, the server side sentry implementation already does
I do agree that the frontend should show some interaction/interface to the user indicating that there was an error
