### ISSUE TITLE
Improve access to keycloak admin in the api

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#354]
Now the password is in the git repo and everybody who has access (public) can read it. When changing the password the CH library needs also be updated. For IFN  the password is in the Codefresh pipeline (helm variable). This works but still the CH library uses the un/pw of the admin. It would be better if the admin can change the password without redeploying

**Comment by filippomc** [comment]
Let's make this backwards compatible and make sure that the user can change the password on keycloak with the change being propagated to the applications that need that connection

**Comment by filippomc** [comment]
This looks like is covered by #361 @zsinnema

**Comment by zsinnema** [comment]
@filippomc I think so too
