### ISSUE TITLE
Use a “role” to connect to keycloak for the CH library instead of the admin/metacell password

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#361]
I want to change the password of the admin. Now the password is in the git repo and everybody who has access (public) can read it. When changing the admin password the pods using the CH library need also be updated

**Comment by zsinnema** [comment]
instead of using a "role" we could also opt for a 2nd username/password pair stored in a secret and generated using the initial username/password. This second pair will only be used for the API. The username/password pair could be auto generated on initial application deployment (as a secret). It will not be stored in the git repo

**Comment by filippomc** [comment]
@zsinnema added the alert as this breaks already existing deployment: the user is not created automatically if it does not exist.
