### ISSUE TITLE
Secrets auto create random passwords

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#387]
Now secrets can be added to applications values files like:

```
harness:
   secrets:
      my-secret-value: "value"
```

This declares the secrets but requires the value to be set statically or in the deployment pipeline.

For the cases where the secret is just internal it would be better to just leave the value empty and let the system create it for us.

Use the strategy used on accounts application: https://github.com/MetaCell/cloud-harness/blob/a71b59e462477ba727904aebf84451372e6e75dc/applications/accounts/deploy/templates/api-user-secret.yaml#L8. Also change accounts to use the new secret declaration strategy

**Comment by zsinnema** [comment]
implemented here: https://github.com/MetaCell/cloud-harness/pull/389

**Comment by filippomc** [comment]
One additional improvement is required.
Atm even if secrets are auto generated, secret entries are added to the codefresh script, like

```
- CUSTOM_apps_accounts_harness_secrets_api__user__username=${{API__USER__USERNAME}}
- CUSTOM_apps_accounts_harness_secrets_api__user__password=${{API__USER__PASSWORD}}
```

This vanishes the secrets auto generated values as setting that variables on codefresh is required.
Since sometimes we want auto-generation, sometimes we cannot auto generate secrets, but still need to set them in the deployment pipeline, I propose to auto generate secrets whenever values are left empty, while force to set as above in the case they are set to some value

**Comment by zsinnema** [comment]
@filippomc do I understand right that in case the secret has a value then we generate the codefresh `CUSTOM_....` entry, if the secret has no value set that we DON'T generate it?

**Comment by filippomc** [comment]
yes that's the only option I can think of without changing the api
