### ISSUE TITLE
Remove Flask dependency from cloudharness_common library

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#401]
In `cloudharness_common` there are parts where the library depends on Flask. E.g. here https://github.com/MetaCell/cloud-harness/blob/68b884d86a97270a29ac97f05961eec54d7d1746/libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py#L5 

The cloudharness common library should be independent on the python framework.

**Comment by filippomc** [comment]
Suggested implementation: use the [contextvar api](https://docs.python.org/3/library/contextvars.html).

In the server:
```python
import contextvars
...
ctx_var = contextvars.ContextVar("bearer")

ctx_var.set(request.headers.get('Authorization', None))
```

Inside the AuthClient

```python
import contextvars
...
ctx_var = contextvars.ContextVar("bearer")

bearer = ctx_var.get()
```
