### ISSUE TITLE
Deployment error: failed to mount cloudharness_kc_accounts secret

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#412]
There is a deployment error in case an application doesn't use Keycloak (ch accounts service):
```
MountVolume.SetUp failed for volume "cloudharness-kc-accounts" : secret "accounts" not found
```

This is because of the fact that the `cloudharness-kc-accounts` secret is always mounted.

Required fix:
only mount the `cloudharness-kc-accounts` secret if there is a "hard" dependecy to `accounts` configured in the values.yaml

**Comment by filippomc** [comment]
Duplicate of #384
