### ISSUE TITLE
The gatekeeper seems not to reload the new configuration after changing harness uri_role_mappings

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#418]
When an application is using `uri_role_mapping` option from cloudharness it seems that after the redeploy the gatekeeper still uses the old configuration. After a pod restart the new configuration is "activated"/"used"

**Comment by filippomc** [comment]
Relates to this: https://github.com/kubernetes/kubernetes/issues/22368. Need to find a way to force pod restart when the configuration changes

**Comment by filippomc** [comment]
Adding an annotation to the pod may be a solution: https://github.com/mock-server/mockserver/issues/992#issuecomment-784133799
