### ISSUE TITLE
Remove caching from the Keycloak library

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#457]
Currently the Keycloak library of Cloud Harness uses the cachetool cached decorator to cache some frequently called functions.

For some applications that is nice (calling many times the KC rest api). 

This issue suggests to remove the caching from the core CH KC library and let the application decide how to optimize it.

**Comment by filippomc** [comment]
Sharing the tests made by @zsinnema: 

Tested 100 calls to get user with id (ac.get_user(user_id))
without cache it took 5.34 seconds, with cache 0.06 seconds
10 repeated calls:
0.06s vs 0.488s

**Comment by zsinnema** [comment]
see also #456
