### ISSUE TITLE
Clean unused database properties from generated values.yaml

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#498]
Properties for databases are specified even if no database is selected. We this we want to remove the useless specifications when they are not needed

**Comment by aranega** [comment]
When no database is used, should the configuration still own an empty entry for `database`?

Like, the `values.yaml` file should contains:
* an empty `database` entry --> `database: {}` ?
* a `database` entrty with a name and nothing else --> `database: {name: appname-db}` ?
* no `database` entry ?
