### ISSUE TITLE
Refactor database options design

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/cloud-harness#567]
Looking at methods like:
https://github.com/MetaCell/cloud-harness/blob/faac12751780b23f138fd8d9a8b69ae50584b1e6/libraries/cloudharness-common/cloudharness/applications.py#L36
I don't think the current strategy to manage the different databases supported is easily maintainable. 
(If we are to add support for a new database we will have to be changing the aforementioned method as well (adding another if))
I would suggest to refactor it to use something like the [strategy design pattern](https://sourcemaking.com/design_patterns/strategy) instead.

**Comment by filippomc** [comment]
@afonsobspinto I think that the level of complexity here is perfectly under control and adding a new database (not in the roadmap atm) is only 2 lines of very simple and readable code.
Better leave complex solutions for complex problems IMO.
