### ISSUE TITLE
Get keycloak user by attribute

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/cloud-harness#664]
I would like to be able to get a keycloak user not by id nor by name but rather by a custom attribute that a keycloak user might have

**Comment by afonsobspinto** [comment]
I was looking into both [cloudharness get_users](https://github.com/MetaCell/cloud-harness/blob/2da748e4dd8ba9336e1551c55adec208dd41fd25/libraries/cloudharness-common/cloudharness/auth/keycloak.py#L377) and also into the [python-keycloak get_users](https://github.com/marcospereirampj/python-keycloak/blob/b3d1a6e088d16ed278495fa8f20308992cc6fcc1/src/keycloak/keycloak_admin.py#L500)

and I don't think there's a way to use the query parameter to obtain what we want since it generates query_strings of the type:

`<realm_domain>/users?<query_key>=<query_value>`

and we seem to need, according to [this](https://stackoverflow.com/a/71838958/16197038) and confirmed locally:

`<realm_domain>/users?q=<query_key>:<query_value>`

**Comment by zsinnema** [comment]
@afonsobspinto can you explain a bit more the use case for this? When do you need this?

**Comment by zsinnema** [comment]
@afonsobspinto so I guess that there is a "unique" identifier of a user (e.g. `email`) . Why can't you use this unique identifier?

**Comment by afonsobspinto** [comment]
Potentially yes, but it's not always true that we can use other attribute like the `email`. 

Not only Keycloak allows duplicate emails but I can also think of a situation where the new application is already in use and an user decided to change his/her email.

**Comment by afonsobspinto** [comment]
https://github.com/marcospereirampj/python-keycloak/issues/362#issuecomment-1192520200

**Comment by zsinnema** [comment]
@afonsobspinto it looks to me that this is "domain specific" data. My advise would be to put the domain specific data in the domain itself and not in Keycloak.
