### ISSUE TITLE
Investigate integration/E2E testing of deployment

### ISSUE THREAD

**Issue by filippomc** [MetaCell/cloud-harness#74]
Some resources to start with:
 - [x]  https://kubernetes.io/blog/2019/03/22/kubernetes-end-to-end-testing-for-everyone/
 - [x] https://github.com/kubernetes-sigs/kubetest2
 - [x] Create cards and estimates for implementation

The goal of this task is defining a strategy and related technologies to run e2s application tests.

**Comment by lrebscher** [comment]
**A strategy could be the following:**

* Tests are run as a [Kubernetes Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/). 
  * There are several approaches to Jobs: From single job for all applications to job per application or job depending on technology requirement (chrome headless browser + puppeter). We are quite flexible here.
* In the simplest case, the Job status is used as indication if tests succeeded/failed. On top of that, test reports can be saved to a PV or any other storage
* During CI deployment, a Python script (`harness-test`) starts & watches the test job(s), interprets the results and finally decides whether deployment should continue or fail


**Some useful sources and notes**

* This is basically the approach that was taken in [this article](https://medium.com/datasparq-technology/integration-tests-in-kubernetes-and-cloud-build-52a2b1023ab3)
* Also interesting but not dealing with application testing, rather as a last step to ensure that K8s resources are in place: https://github.com/bats-core/bats-detik
*  [Cicada](https://cicadatesting.github.io/cicada-2/) is worth a look, also based on yaml configuration, but it doesn't seem to be very flexible and development just started some months ago
* [kubetest2](https://github.com/kubernetes-sigs/kubetest2) and https://kubernetes.io/blog/2019/03/22/kubernetes-end-to-end-testing-for-everyone/ deal rather with testing K8s features than with application tests

**Comment by lrebscher** [comment]
Implementation will be done in #248
