### ISSUE TITLE
Using harness-deploy -m will remove the folder from the repo

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/cloud-harness#97]
steps to reproduce:
git clone ifn
git checkout develop
git clone cloudharness (in .)
git clone mnp (in .)
conda create env and install CH utilities

delete your minikube and install ifn by executing setup.sh
OR
run harness-deployment cloud-harness mnp . -l -m -b -d ifn.local -dtls -i accounts -i argo -i cloudharness-base -i events -i workflows -i mnp-ui -i mnp-checkout -i mnp-ifn -i monitor

you will notice that the applications/accounts will be deleted!
als the mnp/applications/accounts is deleted!

**Comment by filippomc** [comment]
This is resulting to a quick merge implementation. For now, -m can only be used inside codefresh

**Comment by filippomc** [comment]
Now directories are merged in a separate directory, to be specified with the -m option in the harness-deployment script.

After the merge, the codefresh script must be generated from the merged script

For instance after

`harness-generate cloud-harness . -m build`

must run 

`harness-codefresh build` to define a build deployment working from the new merged directory
